export const themeOptions = [
  { value: 'pin', label: 'Pin' },
  { value: 'fork', label: 'Fork' },
  { value: 'skewer', label: 'Skewer' },
  { value: 'xRayAttack', label: 'X-Ray' },
  { value: 'discoveredAttack', label: 'Discovered attack' },
  { value: 'attraction', label: 'Attraction' },
  { value: 'deflection', label: 'Deflection' },
  { value: 'interference', label: 'Interference' },
  { value: 'clearance', label: 'Clearance' },
  { value: 'capturingDefender', label: 'Capture the defender' },
  { value: 'intermezzo', label: 'Intermezzo' },
  { value: 'zugzwang', label: 'Zugzwang' },
  { value: 'quietMove', label: 'Quiet move' },
  { value: 'defensiveMove', label: 'Defensive move' },
  { value: 'opening', label: 'Opening' },
  { value: 'middlegame', label: 'Middlegame' },
  { value: 'endgame', label: 'Endgame' },
  { value: 'mate', label: 'Checkmate' },
  { value: 'enPassant', label: 'En Passant' },
]
